local map = vim.keymap.set

map("n", "<leader>e", "<cmd>NvimTreeToggle<CR>", { desc = "Toggle file tree" })
map("n", "<C-e>", "<cmd>NvimTreeToggle<CR>", { desc = "Toggle file tree" })
map("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Find files" })
map("n", "<C-p>", "<cmd>Telescope find_files<CR>", { desc = "Find files" })
map("n", "<leader>fg", "<cmd>Telescope live_grep<CR>", { desc = "Live grep" })
map("n", "<leader>fb", "<cmd>Telescope buffers<CR>", { desc = "Find buffers" })
map("n", "<leader>fh", "<cmd>Telescope help_tags<CR>", { desc = "Help tags" })
map("n", "<leader>f", function()
  require("conform").format({ async = true, lsp_fallback = true })
end, { desc = "Format file" })
map("n", "<F1>", vim.diagnostic.open_float, { desc = "Show line diagnostics" })
map("n", "<F2>", vim.lsp.buf.definition, { desc = "Go to definition" })
map("n", "<S-F2>", vim.lsp.buf.references, { desc = "List references" })
map("n", "<S-F6>", vim.lsp.buf.rename, { desc = "Rename symbol" })
map("n", "<leader>hs", function()
  require("gitsigns").stage_hunk()
end, { desc = "Stage git hunk" })
map("v", "<leader>hs", function()
  require("gitsigns").stage_hunk({ vim.fn.line("."), vim.fn.line("v") })
end, { desc = "Stage selected git lines" })

local function toggle_comment_current_line()
  require("Comment.api").toggle.linewise.current()
end

map("n", "<C-/>", toggle_comment_current_line, { desc = "Toggle comment" })
map("n", "<C-_>", toggle_comment_current_line, { desc = "Toggle comment" })
map("n", "<C-?>", toggle_comment_current_line, { desc = "Toggle comment" })
