set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm*:Tc"

set -g mouse on

# Use vi-style keys in copy mode and prompts
setw -g mode-keys vi
set -g status-keys vi

# pi
set -g extended-keys on
set -g extended-keys-format csi-u
